version: "3"

services:
  api:
    #restart: always
    stdin_open: true
    tty: true
    build: ./dockerfile
    image: shp2obj:latest
    volumes:
    #  - /home/xuqinghan/dev/flask_test:/code
      - ./src:/deploy/app
